apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: {{ .Values.global.namespace }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: {{ .Values.kafka.name }}
  ports:
    - name: broker
      port: {{ .Values.kafka.ports.client }}
      targetPort: broker

    - name: controller
      port: {{ .Values.kafka.ports.controller }}
      targetPort: controller
