global:
  namespace: monitoring

prometheus:
  image: prom/prometheus:v3.5.0
  serviceAccount:
    name: prometheus

vaultAgent:
  image: hashicorp/vault:1.20

grafana:
  image: grafana/grafana:12.2.0
