apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
  namespace: {{ .Values.global.namespace }}
data:
  vault-agent.hcl: |
    exit_after_auth = false

    vault {
      address = "http://vault.vault.svc.cluster.local:8200"
    }

    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"

        config = {
          role = "prometheus"
        }
      }

      sink "file" {
        config = {
          path = "/vault-token/token"
        }
      }
    }
