apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.notification.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.notification.name }}
  ports:
    - name: http
      port: {{ .Values.notification.port }}
      targetPort: http
