apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: orders-api-key
  namespace: demo
spec:
  vaultAuthRef: orders-service

  mount: kv
  type: kv-v2
  path: orders/api
  refreshAfter: 30s

  destination:
    create: true
    name: orders-service-vault-credentials
