apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.orders.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.orders.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.orders.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.orders.name }}
    spec:
      serviceAccountName: {{ .Values.orders.name }}
      containers:
        - name: {{ .Values.orders.name }}
          image: {{ .Values.orders.image | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.orders.port }}

          volumeMounts:
            - name: orders-service-tls
              mountPath: /etc/tls
              readOnly: true

          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: orders-service-vault-credentials
                  key: API_KEY

            - name: DB_HOST
              value: {{ .Values.postgresql.name | quote }}

            - name: DB_PORT
              value: {{ .Values.postgresql.port | quote }}

            - name: DB_NAME
              value: {{ .Values.postgresql.database | quote }}

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: orders-service-db
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orders-service-db
                  key: password

          readinessProbe:
            httpGet:
              path: /health
              port: http

          livenessProbe:
            httpGet:
              path: /health
              port: http

      volumes:
        - name: orders-service-tls
          secret:
            secretName: orders-service-tls
