apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: orders-service
  namespace: demo
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: kubernetes

  kubernetes:
    role: orders-service
    serviceAccount: orders-service
