apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: orders-service-pki
  namespace: {{ .Values.global.namespace }}
spec:
  vaultAuthRef: orders-service

  mount: pki_int
  role: orders-service

  commonName: orders-service.demo.svc.cluster.local

  destination:
    create: true
    name: orders-service-tls
    type: kubernetes.io/tls
