apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.postgresql.name }}
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.port }}
      targetPort: postgresql
