apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.global.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.orders.name }}
  namespace: {{ .Values.global.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.notification.name }}
  namespace: {{ .Values.global.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.postgresql.name }}
  namespace: {{ .Values.global.namespace }}
