apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.vault.name }}-config
  namespace: {{ .Values.global.namespace }}
data:
  vault.hcl: |
    ui = true

    listener "tcp" {
      address         = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
      tls_disable     = 1
    }

    storage "raft" {
      path    = "{{ .Values.vault.raft.path }}"
      node_id = "VAULT_NODE_ID"
    }

    api_addr     = "http://VAULT_POD_NAME.{{ .Values.vault.name }}-internal.{{ .Values.global.namespace }}.svc.cluster.local:8200"
    cluster_addr = "http://VAULT_POD_NAME.{{ .Values.vault.name }}-internal.{{ .Values.global.namespace }}.svc.cluster.local:8201"

    disable_mlock = true
