apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vault.name }}-internal
  namespace: {{ .Values.global.namespace }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: {{ .Values.vault.name }}
  ports:
    - name: api
      port: {{ .Values.vault.service.apiPort }}
      targetPort: api
    - name: cluster
      port: {{ .Values.vault.service.clusterPort }}
      targetPort: cluster
