apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vault.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.vault.name }}
  ports:
    - name: api
      port: {{ .Values.vault.service.apiPort }}
      targetPort: api
